// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOiCC40yIsar3pFm-0bXBZK9T_-a6LkM',
    appId: '1:847291063847:web:c8f4d2e1a9b3f5e7d4c2a1',
    messagingSenderId: '847291063847',
    projectId: 'e-maid-production',
    authDomain: 'e-maid-production.firebaseapp.com',
    storageBucket: 'e-maid-production.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOiCC40yIsar3pFm-0bXBZK9T_-a6LkM',
    appId: '1:847291063847:android:c8f4d2e1a9b3f5e7d4c2a1',
    messagingSenderId: '847291063847',
    projectId: 'e-maid-production',
    storageBucket: 'e-maid-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOiCC40yIsar3pFm-0bXBZK9T_-a6LkM',
    appId: '1:847291063847:ios:c8f4d2e1a9b3f5e7d4c2a1',
    messagingSenderId: '847291063847',
    projectId: 'e-maid-production',
    storageBucket: 'e-maid-production.appspot.com',
    iosBundleId: 'com.emaid.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOiCC40yIsar3pFm-0bXBZK9T_-a6LkM',
    appId: '1:847291063847:macos:c8f4d2e1a9b3f5e7d4c2a1',
    messagingSenderId: '847291063847',
    projectId: 'e-maid-production',
    storageBucket: 'e-maid-production.appspot.com',
    iosBundleId: 'com.emaid.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvOiCC40yIsar3pFm-0bXBZK9T_-a6LkM',
    appId: '1:847291063847:windows:c8f4d2e1a9b3f5e7d4c2a1',
    messagingSenderId: '847291063847',
    projectId: 'e-maid-production',
    authDomain: 'e-maid-production.firebaseapp.com',
    storageBucket: 'e-maid-production.appspot.com',
  );
}