// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6M9SUSfxtbtV-8DuLilL60bvpxM6Qd0',
    appId: '1:1021594532905:web:44f42bee5a7c6f4be83038',
    messagingSenderId: '1021594532905',
    projectId: 'e-maid-app',
    authDomain: 'e-maid-app.firebaseapp.com',
    storageBucket: 'e-maid-app.firebasestorage.app',
    measurementId: 'G-9S0XWNFZ2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8MzY6kMPOuGY0xvb2tsC3v-p545DY2Do',
    appId: '1:1021594532905:android:bc1b73245925c5f6e83038',
    messagingSenderId: '1021594532905',
    projectId: 'e-maid-app',
    storageBucket: 'e-maid-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8MzY6kMPOuGY0xvb2tsC3v-p545DY2Do',
    appId: '1:1021594532905:ios:bc1b73245925c5f6e83038',
    messagingSenderId: '1021594532905',
    projectId: 'e-maid-app',
    storageBucket: 'e-maid-app.firebasestorage.app',
    iosBundleId: 'com.emaid.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8MzY6kMPOuGY0xvb2tsC3v-p545DY2Do',
    appId: '1:1021594532905:macos:bc1b73245925c5f6e83038',
    messagingSenderId: '1021594532905',
    projectId: 'e-maid-app',
    storageBucket: 'e-maid-app.firebasestorage.app',
    iosBundleId: 'com.emaid.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8MzY6kMPOuGY0xvb2tsC3v-p545DY2Do',
    appId: '1:1021594532905:windows:bc1b73245925c5f6e83038',
    messagingSenderId: '1021594532905',
    projectId: 'e-maid-app',
    authDomain: 'e-maid-app.firebaseapp.com',
    storageBucket: 'e-maid-app.firebasestorage.app',
  );
}
